#!/bin/bash

# Project synchronisation script: remote file differ
# (c) Stephan Nedregaard 2012-
#
# Use freely, but at own responsibility

host="";
user="root";
sources=();

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

host="auto"
user="syncr"
edit="no"

while [[ $# > 0 ]]; do

	key="$1";

	case $key in 
		-h|--host)
			host="$2";
			shift;
			;;
		-u|--user)
			user="$2";
			shift;
			;;
		-e|--edit)
			edit="yes";
			;;
		*)
			sources+=($1);
			;;
	esac
	shift;
done;

if [[ $host == "" ]]; then
	echo No host specified. Add a -h parameter, e.g. -h myhost.mydomain.tld
	exit
fi

for source in "${sources[@]}"; do
	pathlcl=`realpath $source`;
	if [[ $pathlcl == "" ]]; then
		echo "File not found: $source";
		echo "Aborting";
		exit;
	fi;
	if [[ ! -e $pathlcl ]]; then
		source="/Users/stephan/src/$source"
		pathlcl=`realpath $source`;
	fi;
	if [[ ! -e $pathlcl ]]; then
		echo "File not found: $source";
		echo "Aborting";
		exit;
	fi;
	if [[ -d $pathlcl ]]; then
		continue;
	fi;
	lhost="$host"

	if [[ $host == "auto" ]]; then
		dir=$(dirname $pathlcl)
		while [[ ! -e $dir/project.cfg ]]; do
			dir=$(dirname $dir)
			if [[ $dir == "/" ]]; then
				echo "No configuration detected for $pathlcl"
				exit;
			fi
		done
		source $dir/project.cfg
		SRC_DIR=$(dirname $dir)
		lhost=$WWW_HOSTS
	fi

	if [[ $SRC_DIR == "" ]]; then 
		SRC_DIR="$HOME/src"
	fi
	if [[ $DEST_DIR == "" ]]; then
		DEST_DIR="/home/$user/src"
	fi

	path=${pathlcl//$SRC_DIR/$DEST_DIR};

	if [[ $edit == "yes" ]]; then
		echo vimdiff $pathlcl scp://$user@$lhost/$path;
		vimdiff -b $pathlcl scp://$user@$lhost/$path;
	else
		#echo scp $user@$lhost:$path /tmp/remotefile
		scp $user@$lhost:$path /tmp/remotefile &>/dev/null
		difftxt=`diff $pathlcl /tmp/remotefile`;
		if [[ $difftxt == "" ]]; then
			continue;
		fi
		echo "$pathlcl scp://$user@$lhost/$path"
		diff $pathlcl /tmp/remotefile;
		echo 
	fi
done


